### ISSUE TITLE
Error when trying to get pods

### ISSUE THREAD

**Issue by omerlh** [vapor-ware/kubetest#88]
I'm getting the following exception when trying to get pods:
```
env/lib/python3.7/site-packages/kubetest/objects/deployment.py:143: in get_pods
    label_selector=selector_string(self.obj.metadata.labels),
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

selectors = None

    def selector_string(selectors):
        """Create a selector string from the given dictionary of selectors.
    
        Args:
            selectors (dict): The selectors to stringify.
    
        Returns:
            str: The selector string for the given dictionary.
        """
>       return ','.join(['{}={}'.format(k, v) for k, v in selectors.items()])
E       AttributeError: 'NoneType' object has no attribute 'items'

env/lib/python3.7/site-packages/kubetest/utils.py:42: AttributeError
```

This is my code:
```
    d = kube.load_deployment('deployment.yaml')
    
    d.create()
    d.wait_until_ready(timeout=30)
    
    pods = d.get_pods()
    print(pods)

    print("hello")
```

The line ` pods = d.get_pods()` it what causing the error.

This is the deployment file:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kamus-crd-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kamus
      component: crd-controller
  template:
    metadata:
      labels:
        app: kamus
        component: crd-controller
    spec:
      containers:
      - name: controller
        image: crd-controller
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /api/v1/monitoring/isAlice
            port: 9999
```

Can you help me figure it out?

**Comment by marcoceppi** [comment]
Thanks for opening an issue! I don't see anything immediately that would cause this issue. Let us check and get back to you.

**Comment by edaniszewski** [comment]
This issue looks like its related to how we determine which pods belong to a deployment

https://github.com/vapor-ware/kubetest/blob/7db995ce65dfdd37bfcdaf6ec556bc026ee9b323/kubetest/objects/deployment.py#L134-L144

The assumptions we are making are that:
1. The pods are in the same namespace (which they should always be)
2. The pods and the deployment have the same labels.

The second assumption is faulty and originates from some of our use cases that we developed this against. In addition to a deployment not necessarily having the same labels as a pod, a deployment may have no labels, which means this is really two bugs in one.

We can work on a fix for getting a deployment's pods properly. In the mean time, you should be able to get this passing by adding labels to the deployment as well:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kamus-crd-controller
  labels:
    app: kamus
    component: crd-controller
spec:
  ...
```
